# Generated by Django 4.2.2 on 2023-06-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='resto/Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='resto/Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.category')),
            ],
        ),
    ]
